### ISSUE TITLE
ij.viewImage not working with 4D numpy array

### ISSUE THREAD

**Issue by will-moore** [will-moore/omero-imjoy#5]
@oeway I've updated the image loading code to use zarr, using @manzt's zarr-lite, instead of loading a rendered rgb image from OMERO. 
However, I'm having an issue with opening a multi-dimensional image in ImageJ.JS.

For a non-rgb image, where the size of the last dimension is 1, I find that I can only use 3 other dimensions.
Here I have a 4D image (XYZC), which will open if I combine Z and C into a single dimension:

```
ij.viewImage({ _rtype: 'ndarray', _rdtype: 'uint16', _rshape: [sizeZ * sizeC, sizeY, sizeX, 1], _rvalue: zarrPlanes.buffer });
```
at https://github.com/will-moore/omero-imjoy/blob/a1163a22c9c572b10ca5ac1682a18953c0128385/omero_imjoy/templates/omero_imjoy/index.html#L156

However, if I set the shape that I want: `[sizeZ, sizeC, sizeY, sizeX, 1]` then I don't get any image opening in ImageJ.JS (and I don't see any errors).
Any ideas what I'm doing wrong here?

You can run this demo (without `omero-web`) following instructions at:
https://github.com/will-moore/omero-imjoy#dev-testing-without-django

 Thanks

**Comment by oeway** [comment]
I just checked your zarr implementation, does this mean eventually all the omero data will expose a zarr interface?

As I anwsered in [the linked issue](https://github.com/imjoy-team/imagej.js/issues/56), I think you can run a macro to convert a z stack into a hyper stack.

**Comment by will-moore** [comment]
The OME team has been focussing on a micro-service approach to provide a zarr interface to OMERO data: https://github.com/ome/omero-ms-zarr/
However, this doesn't yet provide authentication and the deployment is a little more involved than a simple `pip install` so I have just experimented with providing a zarr interface in this repo since I needed it for this use-case.
However, it doesn't yet support big tiled images.

**Comment by will-moore** [comment]
It works!

![Screenshot 2021-03-18 at 17 06 36](https://user-images.githubusercontent.com/900055/111672566-fe778780-8811-11eb-8a30-0a3b99cb1954.png)
